# This is a basic workflow to help you get started with Actions.
name: iOS CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events for all branches
  push:
    branches: [ "**" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Selects the version of Xcode to use
      #    You can specify a version like '15.3' or leave it as latest
      - name: Select Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      # 3. Executes the build and test commands for your iOS app
      #    You MUST replace 'YourProject.xcodeproj' and 'YourScheme' with your actual project and scheme names.
      - name: Build and Test
        run: |
          xcodebuild clean build test \
          -project YourProject.xcodeproj \
          -scheme YourScheme \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO
